icons_format = "{icon}"

[theme]
theme = "/home/bruno/.config/i3status-rs/themes/tomorrow-night.toml"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon r:$available.eng(w:2)"
[block.theme_overrides]
idle_bg = "#afbfcf"
idle_fg = "#010101"

[[block]]
block = "disk_space"
path = "/var"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "v:$available.eng(w:2) "
[block.theme_overrides]
idle_bg = "#afbfcf"
idle_fg = "#010101"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "h:$available.eng(w:2) "
[block.theme_overrides]
idle_bg = "#afbfcf"
idle_fg = "#010101"

[[block]]
block = "net"
device = "wlp3s0"
interval = 1
format = " $icon wifi $signal_strength down: $graph_down up: $graph_up"
[block.theme_overrides]
idle_bg = "#559905"
idle_fg = "#ffffaa"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
[block.theme_overrides]
idle_bg = "#cc9900"
idle_fg = "#000000"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_bg = "#0055bb"
idle_fg = "#ffffff"
